name: Other type
description: If you use dart or flutter package, please use template
title: "[Other] "
labels:
  - "Type: Bug"
  - "Status: Unconfirmed"
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: Version of repository
      placeholder: ex. 1.0.0
    validations:
      required: false
  - type: textarea
    id: desc
    attributes:
      label: Description of your problem
      description: Please description
      placeholder: Type your info
    render: markdown
  - type: textarea
    id: log
    attributes:
      label: Logs
      description: Your logs
      placeholder: Please wrapper of <details> </details>
      render: sh
    validations:
      required: false
